
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package udv.compi;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int VAL = 14;
  public static final int PYC = 13;
  public static final int PLUS = 9;
  public static final int IGUAL = 12;
  public static final int CC = 5;
  public static final int ID = 15;
  public static final int CA = 4;
  public static final int NUM = 17;
  public static final int DP = 6;
  public static final int TIPO = 11;
  public static final int PRO = 10;
  public static final int LLC = 3;
  public static final int COMMA = 7;
  public static final int LLA = 2;
  public static final int EOF = 0;
  public static final int COMILLA = 8;
  public static final int DOU = 16;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLA",
  "LLC",
  "CA",
  "CC",
  "DP",
  "COMMA",
  "COMILLA",
  "PLUS",
  "PRO",
  "TIPO",
  "IGUAL",
  "PYC",
  "VAL",
  "ID",
  "DOU",
  "NUM"
  };
}

